### ISSUE TITLE
update the icon pics

### ISSUE THREAD

**Issue by simranswaraj** [simranswaraj/simranswaraj.github.io#7]
gre icon pic-
![gre logo](https://user-images.githubusercontent.com/69424315/95298099-27761280-0899-11eb-971f-e75dd17b3ef5.png)
techfiesta pic-
![techfiesta](https://user-images.githubusercontent.com/69424315/95298159-41175a00-0899-11eb-813e-3a47959a407d.jpg)
blood donation pic-
![blood-donation-logo_23-2147506524](https://user-images.githubusercontent.com/69424315/95298191-5096a300-0899-11eb-889b-d596a4f850b2.jpg)
author pic-
![author logo](https://user-images.githubusercontent.com/69424315/95298222-5db39200-0899-11eb-8c82-0d1f4cb4ace1.png)

**Comment by swapnalshahil** [comment]
hey, I will like to do this.

**Comment by simranswaraj** [comment]
yes sure
